Constructor-io/constructorio-node

.travis.yml
README.md

To complete setup, you'll want to create an account @ travis-ci.org using the Constructor-io github profile. Markdown link assumes travis doesn't map our capital profile to lowercase.

Add simple travis test setup

---

lib/constructorio.js
test/constructorio-synonyms.js

Added methods to support the following [synonym REST endpoints](https://docs.constructor.io/rest-api.html#synonyms):
addSynonymGroup => POST https://ac.cnstrc.com/v1/synonym_groups
modifySynonymGroup => PUT https://ac.cnstrc.com/v1/synonym_groups/[group_id]
getSynonymGroups => GET https://ac.cnstrc.com/v1/synonym_groups
getSynonymGroup => GET https://ac.cnstrc.com/v1/synonym_groups/[group_id]
removeSynonymGroups => DELETE https://ac.cnstrc.com/v1/synonym_groups
removeSynonymGroup => DELETE https://ac.cnstrc.com/v1/synonym_groups/[group_id]
33 tests added covering all methods and associated parameters listed above, executing in ~41 seconds.

[CH6629] Synonyms support + tests

---

lib/constructorio.js
test/constructorio-redirects.js
test/constructorio-synonyms.js

Added methods to support the following [redirect rule REST endpoints](https://docs.constructor.io/rest-api.html#redirect-rules):
addRedirectRule => POST https://ac.cnstrc.com/v1/redirect_rules
getRedirectRules => GET https://ac.cnstrc.com/v1/redirect_rules
getRedirectRule => GET https://ac.cnstrc.com/v1/redirect_rules/[redirect_rule_id]
modifyRedirectRule => PUT https://ac.cnstrc.com/v1/redirect_rules/[redirect_rule_id]
updateRedirectRule => PATCH https://ac.cnstrc.com/v1/synonym_groups/[redirect_rule_id]
removeRedirectRule => DELETE https://ac.cnstrc.com/v1/synonym_groups/[redirect_rule_id]
52 tests added covering all methods and associated parameters listed above, executing in ~43 seconds.

[CH6809] Redirects support + tests

---

lib/constructorio.js
test/constructorio-synonyms-one-way.js

* Update `makeUrl` to take an options object
* Add support for One Way Synonyms
* Add tests around One Way Synonyms
Notes:
Still missing a test case around having an empty `child_phrases` array, but should be ready overall and mergeable. Can always add it in later when the issue is resolved.
Discussion about the above here: https://constructor.slack.com/archives/CA44G41HA/p1568830253012600

[CH 7317] One Way Synonyms Support

---

package-lock.json
package.json

- Removed `check-deps` as `npm-check` has a major vulnerability within a dependency and they have not updated the package to resolve, nor do we use it much.
- All tests pass.

Remove check-deps, update dependencies.

---

package.json
spec/mocha.helpers.js
spec/src/modules/tracker.js
src/constructorio.js
src/modules/tracker.js

Adds tracking methods largely inspired by the tracking module from constructorio-client-javascript. The differences are that `userParameters` are passed at method invocation time rather than client invocation time.
As requests originate server side, usual browser request header values need to be supplied within `userParameters`. They are as follows:
`x-cnstrc-token` (supplied at client invocation time)
`X-Forwarded-For`
`Accept-Language`
`Referer`
`User-Agent`
Personalization parameters are also supplied as with other modules.
Tests are comprehensive and ensure all possible request headers are sent correctly for every tracking method.
457/457 tests passing.
98.78% coverage on new tracker module.
93.79% coverage overall.

[CSL-354] Server side tracking

---

README.md
package.json
src/modules/tracker.js

Using the native Node EventEmitter, if you do not bind to an `error` event that is emitted, it will log a stack trace and exit node. It's a good for us to highlight this in the documentation.

Update documentation to highlight the importance of binding an observer to error

---

spec/src/modules/tracker.js
src/modules/tracker.js

`result_id` isn't required for `trackSearchSubmit` - remove.

Remove result_id requirement from trackSearchSubmit.

---

spec/src/modules/tracker.js
src/modules/tracker.js

Port of https://github.com/Constructor-io/constructorio-client-javascript/pull/116
- Any method that used to accept `customer_id` will still do so, but is documented as `item_id` to be more consistent + tests
- Any method that used to accept `name` will still do so, but is documented as `item_name` to be more clear and consistent + tests
- More concise documentation of concepts globally across tracking module
This change does not introduce any breakage to existing implementations / previous versions. We'll need to port these changes to `constructorio-node` once approved.

Consistency of customer_id and item_id's.

---

spec/src/constructorio.js
spec/src/modules/autocomplete.js
spec/src/modules/browse.js
spec/src/modules/catalog.js
spec/src/modules/recommendations.js
spec/src/modules/search.js
spec/src/modules/tracker.js
src/constructorio.js
src/modules/autocomplete.js
src/modules/browse.js
src/modules/catalog.js
src/modules/recommendations.js
src/modules/search.js
src/modules/tracker.js
src/utils/helpers.js

- Ensure reason for rejection is as expected in tests
- Add ability to specify network timeout on client instantiation (can be overridden on each method)
- Sub out timeout functionality to method (thanks @esezen)
- Add more tests, test improvements

[CSL-468] Support fetch timeouts (part 2)

---

src/modules/tracker.js

Pedantic, but in the name of consistency... all of our other documentation examples use 4 spaces.

Update tracking documentation examples to have consistent spacing.

---

scripts/verify-node-version.sh

Node 16 is now active LTS.
✅ All tests pass

Update active LTS codename.

---

spec/src/utils/helpers.js
src/utils/helpers.js

* Add tests
* Update `applyNetworkTimeout` logic
* Not sure why `createAuthHeader` isn't getting coverage even though there's a test around it 🤷

[CSL 731] Add tests around helper functions

---

package-lock.json
package.json
src/constructorio.js
src/nodeFetch.js

Dynamic `import()` confuses ESLint when it's in the main file. Moved it to its own separate file. All tests pass.

[NO-CSL] Move nodeFetch import to another file

---

spec/src/modules/browse.js
spec/src/modules/catalog/catalog-files.js
spec/src/modules/search.js
src/modules/browse.js
src/modules/search.js

* Add support for pre filter expressions
* There's a PR in the integration examples repo that I used to update the products in the Request Test index to test the expressions
* https://github.com/Constructor-io/integration-examples/pull/3
* Might not be super necessary, but good to keep things consistent

[CSL 1971] Add Support for pre filter expresssions

---

cspell.json
spec/src/modules/catalog/catalog-searchabilities.js
src/modules/catalog.js
src/types/catalog.d.ts
src/types/index.d.ts
src/types/tests/catalog.test-d.ts

Adds support for 
https://docs.constructor.io/rest_api/searchabilities/

[CSL-2397] Add support for searchability configurations

---

src/types/index.d.ts
src/types/search.d.ts

- The offset parameter is missing in the SearchParameters type.
- Updated type for Fetch to better reflect Web Standard Fetch API.

Update SearchParameters Type to include offset & Update Fetch Type to Reflect Fetch API

---

src/modules/autocomplete.js
src/modules/browse.js
src/modules/recommendations.js
src/modules/search.js

`testCells` is an optional parameter and not commonly passed. Removing to create more consistency in code examples between client-javascript and this repository.

Remove testCells from examples.

---

package-lock.json
package.json

* Bump node-fetch version from `v3.3.0` to `v3.3.2`
* All tests pass w/ `npm run test` - takes like 7mins run to completion... (`npm run test:parallel` seems to cause tests to fail)
* We have ran into situatations recently where customers using our node client is running into errors when interacting with our API and receiving ECONNRESET
* QB: https://constructor.slack.com/archives/C04KGQHKA14/p1694541811741109
* TVG: https://constructor.slack.com/archives/CA44G41HA/p1694083429476629
* Warren trying to send behavioral requests: https://constructor.slack.com/archives/C01F7U2BYGG/p1674580111134519?thread_ts=1674064401.913649&cid=C01F7U2BYGG
* It seems like this might be due to node-fetch not playing nicely with newer version of node. More details in this [GitHub …

Update node-fetch to v3.3.2

---

src/modules/recommendations.js
src/types/recommendations.d.ts

Hidden Fields aren't added to the request like the client package and therefore cant be retrieved.

Add Hidden Fields to Recommendations Request

---

spec/src/modules/autocomplete.js
spec/src/modules/search.js
src/modules/autocomplete.js
src/modules/search.js

It has been raised that autocomplete requests should not have non-breaking spaces trimmed from queries (terms). This pull request aims to do the following:
a. No longer trim non-breaking spaces from autocomplete and search requests
b. Add tests to cover the above case.
Reference ticket: https://linear.app/constructor/issue/CSL-3108/investigate-error-with-space-input-in-constructorio-node

[CSL-3108] Trim space adjustments

---

spec/mocha.helpers.js
spec/src/modules/tracker.js
src/modules/browse.js
src/modules/recommendations.js
src/modules/tracker.js
src/utils/helpers.js

Related to #183 
Do not trim space from "term" related tracking parameters (`term`, `original_query`, `search_term`)

CSL-3133 Tracking space trimming

---

src/types/quizzes.d.ts
src/types/tests/quizzes.test-d.ts

https://linear.app/constructor/issue/CSL-3107/node-quizzes-updates-total-questions-attribute 
- Adds `total_questions` to the response object type and fixes tests 
[Based on](https://github.com/Constructor-io/constructorio-client-javascript/pull/272)

[CSL-3107] - Add total_questions to the response object type

---

spec/src/modules/quizzes.js

https://linear.app/constructor/issue/CSL-3140/[node]-remove-versionid-from-quizzes-tests
- removes hardcoded versionId from quizz tests and adjusts tests to check it's being passed properly

[csl-3140] - Remove hardcoded versionId from Quizzes tests

---

src/modules/catalog.js

Updates the documentation to reflect the new 10k item limit when
- Uploading Items via the Items API
- Uploading Variations via the Variations API
- Uploading Item Groups via the Item Groups API
I didn't regenerate the docs just yet. Will do so before I merge.

[CSL-3114] Update docs to reflect new 10k limit

---

spec/src/modules/recommendations.js
src/modules/catalog.js
src/modules/recommendations.js

Pass section to getRecommendationPods through parameters.
To maintain backwards compatibility, parameters will be treated as networkParameters in some cases. This is until all customers migrate to using both parameters.

[CI-3342] Pass section to getRecommendationPods

---

cspell.json
spec/src/modules/catalog/catalog-files.js
src/modules/catalog.js

1. Added force flag to 'sync' and 'delta' to have 'forcesync' and 'forcedelta' for tarArchive methods
2. Added email notifications to tarArchive methods
3. Tested notification email and it's working
4. Added tests for requests with notification email and force flag

Add force and notification email to tar archive catalog methods

---

src/types/catalog.d.ts

Changes:
- Adds both `fs.ReadStream` and `Duplex` as possible stream types alongside `File`.
When consuming the node sdk from a node project, we won't have dom types available. In such case we'll most likely use node's native streams, such as `Redable`, `fs.ReadStream` and others.
E.g.

[NO-REF] Fix typescript types for `File` stream in catalog functions

---

spec/src/modules/catalog/catalog-facet-configurations.js
spec/src/modules/catalog/catalog-facet-option-configurations.js
spec/src/modules/catalog/catalog-groups.js
spec/src/modules/catalog/catalog-items.js
spec/src/modules/catalog/catalog-one-way-synonyms.js
spec/src/modules/catalog/catalog-redirect-rules.js
spec/src/modules/catalog/catalog-searchabilities.js
spec/src/modules/catalog/catalog-synonym-groups.js
spec/src/modules/catalog/catalog-variations.js
src/modules/catalog.js

`/catalog` endpoints don't support `c` at the moment. Those will be added later

[CI-3706] A c parameter to catalog module

---

src/modules/tracker.js

Before
* @param {string} [parameters.groupId] - Group identifier of selected item
* @param {string} [parameters.displayName] - Display name of group of selected item
After
* @param {string} [parameters.groupId] - Group identifier of the group to search within if a user elected to search in a group, i.e. "Pumpkin in Canned Goods"
* @param {string} [parameters.displayName] - Display name of the group to search within if a user elected to search in a group, i.e. "Pumpkin in Canned Goods"
Changed in
- trackAutocompleteSelect
- trackSearchSubmit

Update search events group ID documentation

---

spec/src/modules/browse.js
spec/src/modules/catalog/catalog-facet-configurations.js
spec/src/modules/catalog/catalog-items.js
spec/src/modules/catalog/catalog-variations.js
src/modules/catalog.js
src/types/catalog.d.ts

- Update the following mutating functions to return the API call response body instead of resolving an empty promise:
- `createOrReplaceItems`
- `updateItems`
- `deleteItems`
- `createOrReplaceVariations`
- `updateVariations`
- `deleteVariations`
- Fix broken tests related to `getBrowseResults` and `Facet Configurations` cleanup hook

[CI-3858] Resolve body with `task_id` on mutating items and variations functions

---

spec/src/modules/recommendations.js
src/modules/recommendations.js
src/types/recommendations.d.ts

https://constructor.slab.com/posts/adding-variation-id-as-request-parameter-for-recommendation-requests-1sxpt91x#hcqxk-open-questions-uncertainties-risks

[CI 4155] getRecommendations support variation id param

---

spec/src/modules/tracker.js
src/modules/tracker.js
src/utils/helpers.js

Why?
- Focus API events return a text response for the 429 errors
- We only handle JSON response types
- This PR adds support for handling text responses as well by checking the `Content-Type` header before processing the response
The screenshot shows an example of the API response for 429 response

Handle text API responses
