package-lock.json, package.json
`npm audit` reveals no more vulnerable packages:
All tests pass:
=> Update packages to avoid security vulnerabilities.

package-lock.json, package.json
=> Update dependencies to stay up to date with security audit warnings.

spec/src/modules/catalog.js, src/modules/catalog.js
* Add support for Facet Configurations
* Add tests, cleans up after itself (all pass)
* Add support for Facet Option Configurations in a separate PR
=> [CSL 360] Add Support for Facet Configurations

spec/src/csv/item_groups.csv, spec/src/csv/items.csv, spec/src/csv/variations.csv, spec/src/modules/autocomplete.js, spec/src/modules/search.js
This is to match the catalog CSV files and fix broken tests since all 3 repos are using the same index now
=> [CSL-215] Java SDK : Remove API key and token

spec/src/modules/tracker.js, src/modules/tracker.js
Session and client ID should always be required for all tracking calls - enforce in code and update documentation.
=> Improve documentation + require session and user ID for tracking.

src/modules/tracker.js
=> [CSL 475] Gracefully handle userParameters destructuring

package-lock.json, package.json, spec/src/modules/autocomplete.js, spec/src/modules/browse.js, spec/src/modules/catalog.js, spec/src/modules/recommendations.js, spec/src/modules/search.js, spec/src/modules/tracker.js, src/modules/autocomplete.js, src/modules/browse.js, src/modules/catalog.js, src/modules/recommendations.js, src/modules/search.js, src/modules/tracker.js
Add ability to supply timeout via optional `networkParameters` for each method within each module.
=> Initial implementation for timeouts via AbortController.

spec/src/modules/tasks.js, src/constructorio.js, src/modules/tasks.js
=> [CSL 831] ConstructorIO Node - Add support for Tasks

spec/src/modules/tasks.js, src/modules/catalog.js
Fixed bug with removeFacet methods, added test for tasks with page, result_per_page parameters.
=> [CSL-827] Client node improve test coverage

package-lock.json
=> Update dependencies to avoid security vulnerabilities.

spec/src/modules/browse.js, spec/src/modules/search.js, src/modules/browse.js, src/modules/search.js
hiddenFields changed only for search and browse, have another story for autocomplete once backend deploys.
=> [CSL-988] Add support for hidden facets, use fmtOptions for hiddenFields

package-lock.json, package.json
All tests pass except 2 known failing ones
=> [CSL-1131] Update dependencies

spec/src/modules/search.js
Clone of https://github.com/Constructor-io/constructorio-client-javascript/pull/187
=> [NO-CSL] Fix failing hiddenFacets/hiddenMetadata tests

src/modules/catalog.js
* Add examples to catalog module
* Update broken links
* Update `addItem` reference to actually be a link 😄
=> [CSL 1550] Add examples to catalog module

.eslintrc, .github/workflows/lint.yml, cspell.json, package-lock.json, package.json, src/modules/catalog.js
This PR adds the following changes:
- Adds spell checking with [cspell](https://cspell.org/)
- Run spell check via eslint with [@cspell/eslint-plugin](https://www.npmjs.com/package/@cspell/eslint-plugin)
- Add a CI stage to run lint on every PR. Fail in case there are any typos or lint issues.
- None
Whenever we make a typo we get real-time feedback:
As a reviewer, you should test:
- Spell checking
- CI stages
Reproduce the following steps to test:
1. Write some typos
=> [NO-REF] Add spell checking 

spec/src/modules/tracker.js, src/modules/tracker.js
=> support item_name for recommendations click

spec/src/modules/tasks.js, src/modules/tasks.js
Adds support for `type` filter
=> [CSL-1765] Support additional query parameters in `Tasks` module

spec/src/modules/search.js, src/modules/search.js, src/types/search.d.ts
API Documentation
https://docs.constructor.io/rest_api/search/natural_language_search/
Removed parameters because of no API support
- filters
- sort_order
- sort_by
Missing tests
- redirect_rule => if supported
=> [CSL-2072] - Add voice search

cspell.json, spec/src/modules/catalog/catalog-files.js, src/modules/catalog.js, src/types/catalog.d.ts
2 recommendation tests fail on master as well
=> [CSL-2239] Add support for new patch delta endpoints

src/types/index.d.ts, src/types/tracker.d.ts
Port of https://github.com/Constructor-io/constructorio-client-javascript/pull/266 and https://github.com/Constructor-io/constructorio-client-javascript/pull/270
=> [CSL-2655] Update items parameter type in tracker module

spec/src/modules/tracker.js, src/modules/tracker.js, src/types/tracker.d.ts
Port of https://github.com/Constructor-io/constructorio-client-javascript/pull/180
=> [CSL-2690] Add `items` to trackRecommendationView

package-lock.json
Clone of https://github.com/Constructor-io/constructorio-client-javascript/pull/283
=> [CSL-2918] Update dependencies

src/modules/catalog.js, src/types/catalog.d.ts
Force is already supported, just adding to the docs and types
=> [CSL 2970] Add force to the param docs

README.md, docs/index.html
This PR removes the Bundlephobia badge from both the README and the index html file since it´s not working as expected.
=> [CSL-2115] Removed bundlephobia from README and index HTML

spec/src/modules/quizzes.js, src/modules/quizzes.js
Adds page, resultsPerPage, filters parameters
=> [ci-3887] Add misisng parameters

src/modules/quizzes.js
Updating `parameters.answers` docs
=> Quizzes update answers parameter docs
